
LPWSTR Tag_FS_PLC_ASYNCH[450] =
{
	L"WF_1_FLOW_SCL", L"WF_3_FLOW_SCL", L"WF_5_FLOW_SCL", L"WF_7_FLOW_SCL", L"WF_9_FLOW_SCL", L"WF_11_FLOW_SCL",
	L"WF_13_FLOW_SCL", L"WF_15_FLOW_SCL", L"WF_17_FLOW_SCL", L"WF_19_FLOW_SCL", L"WF_21_FLOW_SCL",
	L"WF_23_FLOW_SCL", L"MMI_WF25_ACT_MF_IND", L"MMI_WF27_ACT_MF_IND", L"MMI_WF29_ACT_MF_IND", L"MMI_WF31_ACT_MF_IND",
	L"MMI_WF33_ACT_MF_IND", L"MMI_WF35_ACT_MF_IND", L"MMI_WF37_ACT_MF_IND", L"MMI_WF39_ACT_MF_IND", L"MMI_WF41_ACT_MF_IND",
	L"MMI_WF43_ACT_MF_IND", L"MMI_WF45_ACT_MF_IND", L"MMI_WF_47_FR_IND", L"MMI_WF_49_FR_IND", L"MMI_WF_51_FR_IND", L"MMI_WF_53_FR_IND",

	L"WF_2_FLOW_SCL", L"WF_4_FLOW_SCL", L"WF_6_FLOW_SCL", L"WF_8_FLOW_SCL", L"WF_10_FLOW_SCL",
	L"WF_12_FLOW_SCL", L"WF_14_FLOW_SCL", L"WF_16_FLOW_SCL", L"WF_18_FLOW_SCL", L"WF_20_FLOW_SCL",
	L"WF_22_FLOW_SCL", L"WF_24_FLOW_SCL", L"MMI_WF26_ACT_MF_IND", L"MMI_WF28_ACT_MF_IND", L"MMI_WF30_ACT_MF_IND",
	L"MMI_WF32_ACT_MF_IND", L"MMI_WF34_ACT_MF_IND", L"MMI_WF36_ACT_MF_IND", L"MMI_WF38_ACT_MF_IND", L"MMI_WF40_ACT_MF_IND",
	L"MMI_WF42_ACT_MF_IND", L"MMI_WF44_ACT_MF_IND", L"MMI_WF46_ACT_MF_IND", L"MMI_WF_48_FR_IND", L"MMI_WF_50_FR_IND", L"MMI_WF_52_FR_IND", L"MMI_WF_54_FR_IND",

	L"MMI_WF_2A_FR_IND", L"MMI_WF_4A_FR_IND", L"MMI_WF_6A_FR_IND", L"MMI_WF_8A_FR_IND", L"MMI_WF_10A_FR_IND",
	L"MMI_WF_12A_FR_IND", L"MMI_WF_14A_FR_IND", L"MMI_WF_16A_FR_IND", L"MMI_WF_18A_FR_IND", L"MMI_WF_20A_FR_IND",
	L"MMI_WF_22A_FR_IND", L"MMI_WF_24A_FR_IND", L"MMI_WF_26A_FR_IND", L"MMI_WF_28A_FR_IND", L"MMI_WF_30A_FR_IND",
	L"MMI_WF_32A_FR_IND", L"MMI_WF_34A_FR_IND", L"MMI_WF_36A_FR_IND", L"MMI_WF_38A_FR_IND", L"MMI_WF_40A_FR_IND",
	L"MMI_WF_42A_FR_IND", L"MMI_WF_44A_FR_IND", L"MMI_WF_46A_FR_IND", L"MMI_WF_48A_FR_IND", L"MMI_WF_50A_FR_IND",
	L"MMI_WF_52A_FR_IND", L"MMI_WF_54A_FR_IND",

	L"WF_1_SP_HMI", L"WF_3_SP_HMI", L"WF_5_SP_HMI", L"WF_7_SP_HMI", L"WF_9_SP_HMI", L"WF_11_SP_HMI",
	L"WF_13_SP_HMI", L"WF_15_SP_HMI", L"WF_17_SP_HMI", L"WF_19_SP_HMI", L"WF_21_SP_HMI", L"WF_23_SP_HMI",
	L"MMI_WF25_REF_SP", L"MMI_WF27_REF_SP", L"MMI_WF29_REF_SP", L"MMI_WF31_REF_SP", L"MMI_WF33_REF_SP",
	L"MMI_WF35_REF_SP", L"MMI_WF37_REF_SP", L"MMI_WF39_REF_SP", L"MMI_WF41_REF_SP", L"MMI_WF43_REF_SP",
	L"MMI_WF45_REF_SP", L"MMI_WF_47_REF_FR", L"MMI_WF_49_REF_FR", L"MMI_WF_51_REF_FR", L"MMI_WF_53_REF_FR",

	L"WF_2_SP_HMI", L"WF_4_SP_HMI", L"WF_6_SP_HMI", L"WF_8_SP_HMI", L"WF_10_SP_HMI", L"WF_12_SP_HMI",
	L"WF_14_SP_HMI", L"WF_16_SP_HMI", L"WF_18_SP_HMI", L"WF_20_SP_HMI", L"WF_22_SP_HMI", L"WF_24_SP_HMI",
	L"MMI_WF26_REF_SP", L"MMI_WF28_REF_SP", L"MMI_WF30_REF_SP", L"MMI_WF32_REF_SP", L"MMI_WF34_REF_SP",
	L"MMI_WF36_REF_SP", L"MMI_WF38_REF_SP", L"MMI_WF40_REF_SP", L"MMI_WF42_REF_SP", L"MMI_WF44_REF_SP",
	L"MMI_WF46_REF_SP", L"MMI_WF_48_REF_FR", L"MMI_WF_50_REF_FR", L"MMI_WF_52_REF_FR", L"MMI_WF_54_REF_FR",

	L"MMI_WF_2A_REF_FR", L"MMI_WF_4A_REF_FR", L"MMI_WF_6A_REF_FR", L"MMI_WF_8A_REF_FR", L"MMI_WF_10A_REF_FR",
	L"MMI_WF_12A_REF_FR", L"MMI_WF_14A_REF_FR", L"MMI_WF_16A_REF_FR", L"MMI_WF_18A_REF_FR", L"MMI_WF_20A_REF_FR",
	L"MMI_WF_22A_REF_FR", L"MMI_WF_24A_REF_FR", L"MMI_WF_26A_REF_FR", L"MMI_WF_28A_REF_FR", L"MMI_WF_30A_REF_FR",
	L"MMI_WF_32A_REF_FR", L"MMI_WF_34A_REF_FR", L"MMI_WF_36A_REF_FR", L"MMI_WF_38A_REF_FR", L"MMI_WF_40A_REF_FR",
	L"MMI_WF_42A_REF_FR", L"MMI_WF_44A_REF_FR", L"MMI_WF_46A_REF_FR", L"MMI_WF_48A_REF_FR", L"MMI_WF_50A_REF_FR",
	L"MMI_WF_52A_REF_FR", L"MMI_WF_54A_REF_FR",

	L"WF_1_START_PB", L"WF_3_START_PB", L"WF_5_START_PB", L"WF_7_START_PB", L"WF_9_START_PB",
	L"WF_11_START_PB", L"WF_13_START_PB", L"WF_15_START_PB", L"WF_17_START_PB", L"WF_19_START_PB",
	L"WF_21_START_PB", L"WF_23_START_PB", L"MMI_WF25_START_PB", L"MMI_WF27_START_PB", L"MMI_WF29_START_PB",
	L"MMI_WF31_START_PB", L"MMI_WF33_START_PB", L"MMI_WF35_START_PB", L"MMI_WF37_START_PB", L"MMI_WF39_START_PB",
	L"MMI_WF41_START_PB", L"MMI_WF43_START_PB", L"MMI_WF45_START_PB", L"MMI_WF_47_START_PB", L"MMI_WF_49_START_PB",
	L"MMI_WF_51_START_PB", L"MMI_WF_53_START_PB",
	
	L"WF_2_START_PB", L"WF_4_START_PB", L"WF_6_START_PB", L"WF_8_START_PB", L"WF_10_START_PB",
	L"WF_12_START_PB", L"WF_14_START_PB", L"WF_16_START_PB", L"WF_18_START_PB", L"WF_20_START_PB",
	L"WF_22_START_PB", L"WF_24_START_PB", L"MMI_WF26_START_PB", L"MMI_WF28_START_PB", L"MMI_WF30_START_PB",
	L"MMI_WF32_START_PB", L"MMI_WF34_START_PB", L"MMI_WF36_START_PB", L"MMI_WF38_START_PB", L"MMI_WF40_START_PB",
	L"MMI_WF42_START_PB", L"MMI_WF44_START_PB", L"MMI_WF46_START_PB", L"MMI_WF_48_START_PB", L"MMI_WF_50_START_PB",
	L"MMI_WF_52_START_PB", L"MMI_WF_54_START_PB",

	L"MMI_WF_2A_START_PB", L"MMI_WF_4A_START_PB", L"MMI_WF_6A_START_PB", L"MMI_WF_8A_START_PB", L"MMI_WF_10A_START_PB",
	L"MMI_WF_12A_START_PB", L"MMI_WF_14A_START_PB", L"MMI_WF_16A_START_PB", L"MMI_WF_18A_START_PB", L"MMI_WF_20A_START_PB",
	L"MMI_WF_22A_START_PB", L"MMI_WF_24A_START_PB", L"MMI_WF_26A_START_PB", L"MMI_WF_28A_START_PB", L"MMI_WF_30A_START_PB",
	L"MMI_WF_32A_START_PB", L"MMI_WF_34A_START_PB", L"MMI_WF_36A_START_PB", L"MMI_WF_38A_START_PB", L"MMI_WF_40A_START_PB",
	L"MMI_WF_42A_START_PB", L"MMI_WF_44A_START_PB", L"MMI_WF_46A_START_PB", L"MMI_WF_48A_START_PB", L"MMI_WF_50A_START_PB",
	L"MMI_WF_52A_START_PB", L"MMI_WF_54A_START_PB",

	L"WF_1_STOP_PB", L"WF_3_STOP_PB", L"WF_5_STOP_PB", L"WF_7_STOP_PB", L"WF_9_STOP_PB",
	L"WF_11_STOP_PB", L"WF_13_STOP_PB", L"WF_15_STOP_PB", L"WF_17_STOP_PB", L"WF_19_STOP_PB",
	L"WF_21_STOP_PB", L"WF_23_STOP_PB", L"MMI_WF25_STOP_PB", L"MMI_WF27_STOP_PB", L"MMI_WF29_STOP_PB",
	L"MMI_WF31_STOP_PB", L"MMI_WF33_STOP_PB", L"MMI_WF35_STOP_PB", L"MMI_WF37_STOP_PB", L"MMI_WF39_STOP_PB",
	L"MMI_WF41_STOP_PB", L"MMI_WF43_STOP_PB", L"MMI_WF45_STOP_PB", L"MMI_WF_47_STOP_PB", L"MMI_WF_49_STOP_PB",
	L"MMI_WF_51_STOP_PB", L"MMI_WF_53_STOP_PB",

	L"WF_2_STOP_PB", L"WF_4_STOP_PB", L"WF_6_STOP_PB", L"WF_8_STOP_PB", L"WF_10_STOP_PB",
	L"WF_12_STOP_PB", L"WF_14_STOP_PB", L"WF_16_STOP_PB", L"WF_18_STOP_PB", L"WF_20_STOP_PB",
	L"WF_22_STOP_PB", L"WF_24_STOP_PB", L"MMI_WF26_STOP_PB", L"MMI_WF28_STOP_PB", L"MMI_WF30_STOP_PB",
	L"MMI_WF32_STOP_PB", L"MMI_WF34_STOP_PB", L"MMI_WF36_STOP_PB", L"MMI_WF38_STOP_PB", L"MMI_WF40_STOP_PB",
	L"MMI_WF42_STOP_PB", L"MMI_WF44_STOP_PB", L"MMI_WF46_STOP_PB", L"MMI_WF_48_STOP_PB", L"MMI_WF_50_STOP_PB",
	L"MMI_WF_52_STOP_PB", L"MMI_WF_54_STOP_PB",

	L"MMI_WF_2A_STOP_PB", L"MMI_WF_4A_STOP_PB", L"MMI_WF_6A_STOP_PB", L"MMI_WF_8A_STOP_PB", L"MMI_WF_10A_STOP_PB",
	L"MMI_WF_12A_STOP_PB", L"MMI_WF_14A_STOP_PB", L"MMI_WF_16A_STOP_PB", L"MMI_WF_18A_STOP_PB", L"MMI_WF_20A_STOP_PB",
	L"MMI_WF_22A_STOP_PB", L"MMI_WF_24A_STOP_PB", L"MMI_WF_26A_STOP_PB", L"MMI_WF_28A_STOP_PB", L"MMI_WF_30A_STOP_PB",
	L"MMI_WF_32A_STOP_PB", L"MMI_WF_34A_STOP_PB", L"MMI_WF_36A_STOP_PB", L"MMI_WF_38A_STOP_PB", L"MMI_WF_40A_STOP_PB",
	L"MMI_WF_42A_STOP_PB", L"MMI_WF_44A_STOP_PB", L"MMI_WF_46A_STOP_PB", L"MMI_WF_48A_STOP_PB", L"MMI_WF_50A_STOP_PB",
	L"MMI_WF_52A_STOP_PB", L"MMI_WF_54A_STOP_PB",

	L"WF_1_TOT_IND", L"WF_3_TOT_IND", L"WF_5_TOT_IND", L"WF_7_TOT_IND", L"WF_9_TOT_IND",
	L"WF_11_TOT_IND", L"WF_13_TOT_IND", L"WF_15_TOT_IND", L"WF_17_TOT_IND", L"WF_19_TOT_IND",
	L"WF_21_TOT_IND", L"WF_23_TOT_IND", L"WF_25_TOT_IND", L"WF_27_TOT_IND", L"WF_29_TOT_IND",
	L"WF_31_TOT_IND", L"WF_33_TOT_IND", L"WF_35_TOT_IND", L"WF_37_TOT_IND", L"WF_39_TOT_IND",
	L"WF_41_TOT_IND", L"WF_43_TOT_IND", L"WF_45_TOT_IND", L"MMI_WF_47_TOTALIZER_IND", L"MMI_WF_49_TOTALIZER_IND",
	L"MMI_WF_51_TOTALIZER_IND", L"MMI_WF_53_TOTALIZER_IND",

	L"WF_2_TOT_IND", L"WF_4_TOT_IND", L"WF_6_TOT_IND", L"WF_8_TOT_IND", L"WF_10_TOT_IND",
	L"WF_12_TOT_IND", L"WF_14_TOT_IND", L"WF_16_TOT_IND", L"WF_18_TOT_IND", L"WF_20_TOT_IND",
	L"WF_22_TOT_IND", L"WF_24_TOT_IND", L"WF_26_TOT_IND", L"WF_28_TOT_IND", L"WF_30_TOT_IND",
	L"WF_32_TOT_IND", L"WF_34_TOT_IND", L"WF_36_TOT_IND", L"WF_38_TOT_IND", L"WF_40_TOT_IND",
	L"WF_42_TOT_IND", L"WF_44_TOT_IND", L"WF_46_TOT_IND", L"MMI_WF_48_TOTALIZER_IND", L"MMI_WF_50_TOTALIZER_IND",
	L"MMI_WF_52_TOTALIZER_IND", L"MMI_WF_54_TOTALIZER_IND",

	L"MMI_WF_2A_TOTALIZER_IND", L"MMI_WF_4A_TOTALIZER_IND", L"MMI_WF_6A_TOTALIZER_IND", L"MMI_WF_8A_TOTALIZER_IND", L"MMI_WF_10A_TOTALIZER_IND",
	L"MMI_WF_12A_TOTALIZER_IND", L"MMI_WF_14A_TOTALIZER_IND", L"MMI_WF_16A_TOTALIZER_IND", L"MMI_WF_18A_TOTALIZER_IND", L"MMI_WF_20A_TOTALIZER_IND",
	L"MMI_WF_22A_TOTALIZER_IND", L"MMI_WF_24A_TOTALIZER_IND", L"MMI_WF_26A_TOTALIZER_IND", L"MMI_WF_28A_TOTALIZER_IND", L"MMI_WF_30A_TOTALIZER_IND",
	L"MMI_WF_32A_TOTALIZER_IND", L"MMI_WF_34A_TOTALIZER_IND", L"MMI_WF_36A_TOTALIZER_IND", L"MMI_WF_38A_TOTALIZER_IND", L"MMI_WF_40A_TOTALIZER_IND",
	L"MMI_WF_42A_TOTALIZER_IND", L"MMI_WF_44A_TOTALIZER_IND", L"MMI_WF_46A_TOTALIZER_IND", L"MMI_WF_48A_TOTALIZER_IND", L"MMI_WF_50A_TOTALIZER_IND",
	L"MMI_WF_52A_TOTALIZER_IND", L"MMI_WF_54A_TOTALIZER_IND",

	L"MMI_Y9_RUN_IND", L"MMI_Y10_RUN_IND", L"MMI_Y10A_RUN_IND"

};

int no_of_tags_FS_PLC_ASYNCH = 408;


